services:
  - type: web
    name: nopaper-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_PORT
        value: "3306"
      - key: MYSQL_DB
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        sync: false

databases:
  - name: nopaper-db
    databaseName: online_bookshop
    user: nopaper

